print('HELLO PYTHON')
print('Hello Python')
print('Hello Python')
print('Hello Git')
import turtle

screen = turtle.Screen()
screen.setup(800,800)
screen.title('憤怒鳥')
#身體
body = turtle.Turtle()
body.color('black','yellow')
body.pensize(10)
body.begin_fill()
body.speed(0)
leng = 4
for i in range(leng):
	body.forward(300)
	body.circle(50,360//leng)
body.end_fill()
body.hideturtle()
#眼睛
eye = turtle.Turtle()
eye.shape('circle')
eye.shapesize(8,6,10)
eye.color('black','white')
eye.penup()
eye.goto(180,250)
eye.stamp()
eye.goto(300,250)
eye.stamp()

#眼球
eyeball = turtle.Turtle()
eyeball.penup()
eyeball.hideturtle()
eyeball.shape('circle')
eyeball.shapesize(4,3)
eyeball.color('black','black')
eyeball.goto(200,270)
eyeball.stamp()
eyeball.goto(280,270)
eyeball.stamp()

#眉毛
eyebrow = turtle.Turtle()
eyebrow.penup()
eyebrow.hideturtle()
eyebrow.shape('square')
eyebrow.pensize(50)
eyebrow.goto(180,350)
eyebrow.pendown()
eyebrow.goto(240,280)
eyebrow.goto(300,350)
eyebrow.penup()

#嘴巴
mouth = turtle.Turtle()
mouth.penup()
mouth.color('black','orange')
mouth.hideturtle()
mouth.pensize(10)
mouth.begin_fill()
mouth.goto(200,100)
mouth.pendown()
mouth.goto(300,100)
mouth.goto(280,150)
mouth.goto(180,150)
mouth.goto(200,100)
mouth.end_fill()

mouth.color('black','brown')
mouth.penup()
mouth.begin_fill()
mouth.goto(270,145)
mouth.goto(185,145)
mouth.goto(290,110)
mouth.goto(270,145)
mouth.end_fill()

mouth.penup()
mouth.color('black','orange')
mouth.hideturtle()
mouth.pensize(10)
mouth.begin_fill()
mouth.goto(180,150)
mouth.pendown()
mouth.goto(330,150)
mouth.goto(250,200)
mouth.goto(180,150)
mouth.end_fill()

screen.mainloop()


screen.getcanvas().postscript(file="angrybird.ps", colormode='color')
